### ISSUE TITLE
集計結果をDMに送るか、timesに送るかを分岐させる処理追加

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.VCtimeRecord#47]
# 依頼
```
もしできるなら…個人集計をtimesに載せていただけるとありがたいですすす
```
https://discord.com/channels/603582455756095488/603586209159053312/836503097874317373

# 要件
- 集計結果をdmでなく、timesに送信できたらいい
- なぜか
  - timesに送信されると他人の目にも触れ、交流が生まれる
  - DMに画面を移動するのが手間

## 現在
- 特定のメッセージにリアクションをすることで集計結果がDMに送られる
## 今後
- ユーザー毎にDMではなく、timesに送って欲しい人は特定の設定を行う（DBに保存）
- 特定のメッセージにリアクションをすることで集計結果は
  - timesに送って欲しいという設定がDBにあるユーザーはtimesに送信する
    - timesが存在しない場合には、エラー文をDMに送信する
  - その設定が存在しない場合はデフォルトでDMに送信する
  
  ## 検討
  - 処理の流れ
    1. 特定のメッセージにリアクションを押す
    2. リアクションに応じて集計する処理を分岐する
    3. DBにクエリを投げて、特定のテーブルにtimesに結果を送りたい設定が存在するか判定する
    4. 設定が存在するユーザーであり、timesが存在すればtimesに集計結果を送信する
    5.  4で処理がされなければ、DMに送信される
- この設定の仕方をどうやって新しいメンバーに伝えるか

**Comment by nntsugu** [comment]
リアクションを2種用意して出し分けすればいいんじゃない？

**Comment by su-pleiades** [comment]
正直そっちの方がかなり楽だと思う！コード弄るだけだからね👍
それとdbに設定値置くと、それをユーザーがコマンドで設定値を登録したり、切り替えたりする手間やコマンド事態を認識しないといけない手間も増えるよね😥これするなら遅いけど何処のチャンネルにbotコマンドの説明まとめようと思う

それもそうだな〜と思いつつ、
dbに設定値を置いてbotで扱うこと今後現れそうだと予想してこれをいい勉強としてそういう処理を作ってみるかな🤔
dbとコードやら、つぐさん案よりdb案は余計にコストかかるから躓きが酷ければリアクション式にすぐ切りかえて作ってみる！

なので出先から帰宅した月火水あたりで作れなかったら、つぐさん案で！とりあえずは自分の勉強として遊んでみま🙌

**Comment by nntsugu** [comment]
DBを触りたい気持ちはわかるが道具に引きずられてユーザの利便性を損なうのは本末転倒だよ。

**Comment by su-pleiades** [comment]
確認すると
この画像にある6つの説明とリアクションを2倍にする認識であってる？
![image](https://user-images.githubusercontent.com/45380191/116774245-48e95680-aa96-11eb-9839-571ddbf15f7f.png)

**Comment by nntsugu** [comment]
数が多いなら部屋を分けるのもいいかもね。

**Comment by su-pleiades** [comment]
そしたら使いたいと思ってるユーザーに相談してみるね

🌾以下書きなぐりの情報、見直し特になし。
情報書き出し

(以前、現状情報)
今後timesが足りないことを見越してtimesの数を管理する1つとしてtimesを減らす
（今後メンバー全自動管理よりtimesを活用してないチャンネルは例えば1ヶ月使用しないと警告後削除を自動管理する）
timesが勉強集計出力専用になってしまっているチャンネルの除外化
それらを想定して出力結果をDMへ
（フィードバック）
既存ユーザーの集計結果にスタンプで交流する環境を求めるユーザーがいた

（このシステムの今後の前提）
運営側のモチベーションとして500人以上参加する日本勉強サーバーを目標に置く
メンバー整理は基本しない(メンバー上限を気にする必要が無いため。今までの直近2ヶ月勉強している人のみ在籍のルールを解除するつもり。メンバー整理は気を使う作業のため)
メンバー整理をしない代わりに（勉強している人と幽霊部員が少しでも可視化される仕組みは作っていきたい、例えば役職を活用した何か参考は以下）
![image](https://user-images.githubusercontent.com/45380191/116775090-daa79280-aa9b-11eb-88b9-e5b4e4a3c252.jpeg)
timesはチャンネル上限500個の為、自動整理を行う（参加人数が500人を超えることを頭に入れて今後のものづくりをする上で、まずはtimesの整理。timesが削除された場合、その後必要になった場合にコマンドや何かでユーザー自身必要な時に作れる仕組み作りを行う）

✅設定値をdbに置く版
メリット
、見た目は今のまま変わらない
、times送信者も1度設定することでそれ以降はdm,timesの送信先を判断する必要が無くなる
、開発者としては今回の新規コードを今後流用可
、ギルドとしてのデフォルト設定（推奨）を定められる
デメリット
、設定の手間がある
、設定方法を周知する方法が必要（口頭で伝えるのと知っている人のみな方法はだめ。やるならリアクションの上あたりに「もしtimesに送信したい場合は（リアクションorコマンド）で設定してみてね」などの説明文をチャンネルごとに追記）

✅手間な設定を無くし全てユーザーが分かるようtimesとdmそれぞれの処理用のリアクションとその処理の説明を作成する版
メリット
、設定する手間がない
、開発者は既存コードをコピーして処理を少し変更するだけでいい
、文章を読めばどのような宛先に結果が飛ぶのか分かるので、誰かに教えてもらったり、別途チャンネルから処理の説明などを読む必要が無い
デメリット
、リアクションを押す時に押すボタンを判断する一瞬の材料が増える



ここまで雑に書き出す中で書き出す中で
目的は、
「ユーザーにとってギルドの求める方針に乗っ取りつつも利便性を尊重した作りにすること」
になる。
整理して私個人の現段階の新しい発想を書き出す
🤍ユーザーから見える既存の見え方は変わらず、それに、追加する形でユーザー設定をリアクションで変更できるようにする
（極力コマンドにて何かを処理するのをなるべく減らす方向）
![image](https://user-images.githubusercontent.com/45380191/116775620-f3657780-aa9e-11eb-9a0f-050ebc0ea4b8.jpeg)
🤍追加したユーザー設定（(仮)）の中で、リアクションをひとつ押すとデフォルド（dm）からtimesに送信する設定をdbに追加する。再度押すとtimesからdmに戻すのを繰り返す

追加
🤍現在の設定を確認する処理が必要（集計結果の処理を動かして、どっち宛に送信されるか確認するでもありだが）なのと、設定変更したことを知らせるメッセージをdmに送るなどを行いユーザーが設定変更完了したことを確認できるようにする

**Comment by su-pleiades** [comment]
次の段階や最終的にどんな形になるかまだ分からないけど
1人だと考え偏ってたから、アドバイスと刺激をありがとう😘

**Comment by supleiades** [comment]
# 動作確認
- ボタン１と２は想定通り（今まで通り）
![image](https://user-images.githubusercontent.com/45380191/121459912-0e54d100-c9e7-11eb-98a8-5d0a20870428.png)

- ボタン３と４はtimesに飛ぶ
![image](https://user-images.githubusercontent.com/45380191/121459941-2167a100-c9e7-11eb-9364-28e07c8a3e85.png)

**Comment by supleiades** [comment]
# 追加
- timesの場合はメンション欲しいな（通知、ポップアップを押して移動できる快適さが欲しい）

**Comment by supleiades** [comment]
- 以下のコードを追加したら、こんな感じに表示されて特にメンションされた通知は届かなかった
```py
                    embed.add_field(name="to: ",value=member.mention)
```
- 結果
![image](https://user-images.githubusercontent.com/45380191/121460901-bc14af80-c9e8-11eb-87b3-97e909ed85e0.png)

**Comment by supleiades** [comment]
それなら、メンションするより
「timesに送信しました」（現在３秒）を
「{チャンネルへのリンク（メンション）}に送信しました」をtimes移動処理と同じ5秒にする方が良さそうかも
