### ISSUE TITLE
旧リポジトリの停止とコメント記載、新リポジトリの整理

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.VCtimeRecord#8]
# リポジトリ整理
## 旧リポジトリ
- 基本的な全てのファイルのコードを消して、コメントをつけて使用していないことを表記する
## 新リポジトリ
- 旧リポジトリから必要なissueを移動
- 別リポジトリで動いているコードを削除
- 必要なものと、必要かな？と思われるものだけ残す

**Comment by su-pleiades** [comment]
この作業の対応を今後行っていく
https://github.com/mo9mo9study/discord.VCtimeRecord/issues/4

**Comment by su-pleiades** [comment]
一旦、現状動いている機能だけmasterにして整理する
その他をdevelopブランチとしてファイルの一時退避先として作業を進めていく

**Comment by supleiades** [comment]
旧リポジトリの対応は終わっているのでクローズ
